// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="standalone_mmult,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=1192,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=160,HLS_SYN_FF=16368,HLS_SYN_LUT=24142}" *)

module standalone_mmult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_0_address0,
        A_0_ce0,
        A_0_q0,
        A_0_address1,
        A_0_ce1,
        A_0_q1,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        A_1_address1,
        A_1_ce1,
        A_1_q1,
        A_2_address0,
        A_2_ce0,
        A_2_q0,
        A_2_address1,
        A_2_ce1,
        A_2_q1,
        A_3_address0,
        A_3_ce0,
        A_3_q0,
        A_3_address1,
        A_3_ce1,
        A_3_q1,
        A_4_address0,
        A_4_ce0,
        A_4_q0,
        A_4_address1,
        A_4_ce1,
        A_4_q1,
        A_5_address0,
        A_5_ce0,
        A_5_q0,
        A_5_address1,
        A_5_ce1,
        A_5_q1,
        A_6_address0,
        A_6_ce0,
        A_6_q0,
        A_6_address1,
        A_6_ce1,
        A_6_q1,
        A_7_address0,
        A_7_ce0,
        A_7_q0,
        A_7_address1,
        A_7_ce1,
        A_7_q1,
        A_8_address0,
        A_8_ce0,
        A_8_q0,
        A_8_address1,
        A_8_ce1,
        A_8_q1,
        A_9_address0,
        A_9_ce0,
        A_9_q0,
        A_9_address1,
        A_9_ce1,
        A_9_q1,
        A_10_address0,
        A_10_ce0,
        A_10_q0,
        A_10_address1,
        A_10_ce1,
        A_10_q1,
        A_11_address0,
        A_11_ce0,
        A_11_q0,
        A_11_address1,
        A_11_ce1,
        A_11_q1,
        A_12_address0,
        A_12_ce0,
        A_12_q0,
        A_12_address1,
        A_12_ce1,
        A_12_q1,
        A_13_address0,
        A_13_ce0,
        A_13_q0,
        A_13_address1,
        A_13_ce1,
        A_13_q1,
        A_14_address0,
        A_14_ce0,
        A_14_q0,
        A_14_address1,
        A_14_ce1,
        A_14_q1,
        A_15_address0,
        A_15_ce0,
        A_15_q0,
        A_15_address1,
        A_15_ce1,
        A_15_q1,
        B_0_address0,
        B_0_ce0,
        B_0_q0,
        B_0_address1,
        B_0_ce1,
        B_0_q1,
        B_1_address0,
        B_1_ce0,
        B_1_q0,
        B_1_address1,
        B_1_ce1,
        B_1_q1,
        B_2_address0,
        B_2_ce0,
        B_2_q0,
        B_2_address1,
        B_2_ce1,
        B_2_q1,
        B_3_address0,
        B_3_ce0,
        B_3_q0,
        B_3_address1,
        B_3_ce1,
        B_3_q1,
        B_4_address0,
        B_4_ce0,
        B_4_q0,
        B_4_address1,
        B_4_ce1,
        B_4_q1,
        B_5_address0,
        B_5_ce0,
        B_5_q0,
        B_5_address1,
        B_5_ce1,
        B_5_q1,
        B_6_address0,
        B_6_ce0,
        B_6_q0,
        B_6_address1,
        B_6_ce1,
        B_6_q1,
        B_7_address0,
        B_7_ce0,
        B_7_q0,
        B_7_address1,
        B_7_ce1,
        B_7_q1,
        B_8_address0,
        B_8_ce0,
        B_8_q0,
        B_8_address1,
        B_8_ce1,
        B_8_q1,
        B_9_address0,
        B_9_ce0,
        B_9_q0,
        B_9_address1,
        B_9_ce1,
        B_9_q1,
        B_10_address0,
        B_10_ce0,
        B_10_q0,
        B_10_address1,
        B_10_ce1,
        B_10_q1,
        B_11_address0,
        B_11_ce0,
        B_11_q0,
        B_11_address1,
        B_11_ce1,
        B_11_q1,
        B_12_address0,
        B_12_ce0,
        B_12_q0,
        B_12_address1,
        B_12_ce1,
        B_12_q1,
        B_13_address0,
        B_13_ce0,
        B_13_q0,
        B_13_address1,
        B_13_ce1,
        B_13_q1,
        B_14_address0,
        B_14_ce0,
        B_14_q0,
        B_14_address1,
        B_14_ce1,
        B_14_q1,
        B_15_address0,
        B_15_ce0,
        B_15_q0,
        B_15_address1,
        B_15_ce1,
        B_15_q1,
        C_address0,
        C_ce0,
        C_we0,
        C_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] A_0_address0;
output   A_0_ce0;
input  [31:0] A_0_q0;
output  [5:0] A_0_address1;
output   A_0_ce1;
input  [31:0] A_0_q1;
output  [5:0] A_1_address0;
output   A_1_ce0;
input  [31:0] A_1_q0;
output  [5:0] A_1_address1;
output   A_1_ce1;
input  [31:0] A_1_q1;
output  [5:0] A_2_address0;
output   A_2_ce0;
input  [31:0] A_2_q0;
output  [5:0] A_2_address1;
output   A_2_ce1;
input  [31:0] A_2_q1;
output  [5:0] A_3_address0;
output   A_3_ce0;
input  [31:0] A_3_q0;
output  [5:0] A_3_address1;
output   A_3_ce1;
input  [31:0] A_3_q1;
output  [5:0] A_4_address0;
output   A_4_ce0;
input  [31:0] A_4_q0;
output  [5:0] A_4_address1;
output   A_4_ce1;
input  [31:0] A_4_q1;
output  [5:0] A_5_address0;
output   A_5_ce0;
input  [31:0] A_5_q0;
output  [5:0] A_5_address1;
output   A_5_ce1;
input  [31:0] A_5_q1;
output  [5:0] A_6_address0;
output   A_6_ce0;
input  [31:0] A_6_q0;
output  [5:0] A_6_address1;
output   A_6_ce1;
input  [31:0] A_6_q1;
output  [5:0] A_7_address0;
output   A_7_ce0;
input  [31:0] A_7_q0;
output  [5:0] A_7_address1;
output   A_7_ce1;
input  [31:0] A_7_q1;
output  [5:0] A_8_address0;
output   A_8_ce0;
input  [31:0] A_8_q0;
output  [5:0] A_8_address1;
output   A_8_ce1;
input  [31:0] A_8_q1;
output  [5:0] A_9_address0;
output   A_9_ce0;
input  [31:0] A_9_q0;
output  [5:0] A_9_address1;
output   A_9_ce1;
input  [31:0] A_9_q1;
output  [5:0] A_10_address0;
output   A_10_ce0;
input  [31:0] A_10_q0;
output  [5:0] A_10_address1;
output   A_10_ce1;
input  [31:0] A_10_q1;
output  [5:0] A_11_address0;
output   A_11_ce0;
input  [31:0] A_11_q0;
output  [5:0] A_11_address1;
output   A_11_ce1;
input  [31:0] A_11_q1;
output  [5:0] A_12_address0;
output   A_12_ce0;
input  [31:0] A_12_q0;
output  [5:0] A_12_address1;
output   A_12_ce1;
input  [31:0] A_12_q1;
output  [5:0] A_13_address0;
output   A_13_ce0;
input  [31:0] A_13_q0;
output  [5:0] A_13_address1;
output   A_13_ce1;
input  [31:0] A_13_q1;
output  [5:0] A_14_address0;
output   A_14_ce0;
input  [31:0] A_14_q0;
output  [5:0] A_14_address1;
output   A_14_ce1;
input  [31:0] A_14_q1;
output  [5:0] A_15_address0;
output   A_15_ce0;
input  [31:0] A_15_q0;
output  [5:0] A_15_address1;
output   A_15_ce1;
input  [31:0] A_15_q1;
output  [5:0] B_0_address0;
output   B_0_ce0;
input  [31:0] B_0_q0;
output  [5:0] B_0_address1;
output   B_0_ce1;
input  [31:0] B_0_q1;
output  [5:0] B_1_address0;
output   B_1_ce0;
input  [31:0] B_1_q0;
output  [5:0] B_1_address1;
output   B_1_ce1;
input  [31:0] B_1_q1;
output  [5:0] B_2_address0;
output   B_2_ce0;
input  [31:0] B_2_q0;
output  [5:0] B_2_address1;
output   B_2_ce1;
input  [31:0] B_2_q1;
output  [5:0] B_3_address0;
output   B_3_ce0;
input  [31:0] B_3_q0;
output  [5:0] B_3_address1;
output   B_3_ce1;
input  [31:0] B_3_q1;
output  [5:0] B_4_address0;
output   B_4_ce0;
input  [31:0] B_4_q0;
output  [5:0] B_4_address1;
output   B_4_ce1;
input  [31:0] B_4_q1;
output  [5:0] B_5_address0;
output   B_5_ce0;
input  [31:0] B_5_q0;
output  [5:0] B_5_address1;
output   B_5_ce1;
input  [31:0] B_5_q1;
output  [5:0] B_6_address0;
output   B_6_ce0;
input  [31:0] B_6_q0;
output  [5:0] B_6_address1;
output   B_6_ce1;
input  [31:0] B_6_q1;
output  [5:0] B_7_address0;
output   B_7_ce0;
input  [31:0] B_7_q0;
output  [5:0] B_7_address1;
output   B_7_ce1;
input  [31:0] B_7_q1;
output  [5:0] B_8_address0;
output   B_8_ce0;
input  [31:0] B_8_q0;
output  [5:0] B_8_address1;
output   B_8_ce1;
input  [31:0] B_8_q1;
output  [5:0] B_9_address0;
output   B_9_ce0;
input  [31:0] B_9_q0;
output  [5:0] B_9_address1;
output   B_9_ce1;
input  [31:0] B_9_q1;
output  [5:0] B_10_address0;
output   B_10_ce0;
input  [31:0] B_10_q0;
output  [5:0] B_10_address1;
output   B_10_ce1;
input  [31:0] B_10_q1;
output  [5:0] B_11_address0;
output   B_11_ce0;
input  [31:0] B_11_q0;
output  [5:0] B_11_address1;
output   B_11_ce1;
input  [31:0] B_11_q1;
output  [5:0] B_12_address0;
output   B_12_ce0;
input  [31:0] B_12_q0;
output  [5:0] B_12_address1;
output   B_12_ce1;
input  [31:0] B_12_q1;
output  [5:0] B_13_address0;
output   B_13_ce0;
input  [31:0] B_13_q0;
output  [5:0] B_13_address1;
output   B_13_ce1;
input  [31:0] B_13_q1;
output  [5:0] B_14_address0;
output   B_14_ce0;
input  [31:0] B_14_q0;
output  [5:0] B_14_address1;
output   B_14_ce1;
input  [31:0] B_14_q1;
output  [5:0] B_15_address0;
output   B_15_ce0;
input  [31:0] B_15_q0;
output  [5:0] B_15_address1;
output   B_15_ce1;
input  [31:0] B_15_q1;
output  [9:0] C_address0;
output   C_ce0;
output   C_we0;
output  [31:0] C_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_mmult_hw_float_32_s_fu_74_ap_start;
wire    grp_mmult_hw_float_32_s_fu_74_ap_done;
wire    grp_mmult_hw_float_32_s_fu_74_ap_idle;
wire    grp_mmult_hw_float_32_s_fu_74_ap_ready;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_0_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_0_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_0_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_0_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_1_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_1_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_1_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_1_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_2_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_2_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_2_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_2_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_3_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_3_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_3_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_3_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_4_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_4_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_4_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_4_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_5_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_5_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_5_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_5_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_6_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_6_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_6_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_6_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_7_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_7_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_7_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_7_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_8_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_8_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_8_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_8_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_9_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_9_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_9_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_9_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_10_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_10_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_10_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_10_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_11_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_11_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_11_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_11_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_12_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_12_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_12_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_12_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_13_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_13_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_13_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_13_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_14_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_14_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_14_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_14_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_15_address0;
wire    grp_mmult_hw_float_32_s_fu_74_a_15_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_a_15_address1;
wire    grp_mmult_hw_float_32_s_fu_74_a_15_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_0_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_0_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_0_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_0_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_1_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_1_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_1_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_1_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_2_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_2_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_2_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_2_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_3_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_3_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_3_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_3_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_4_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_4_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_4_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_4_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_5_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_5_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_5_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_5_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_6_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_6_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_6_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_6_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_7_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_7_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_7_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_7_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_8_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_8_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_8_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_8_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_9_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_9_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_9_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_9_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_10_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_10_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_10_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_10_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_11_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_11_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_11_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_11_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_12_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_12_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_12_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_12_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_13_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_13_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_13_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_13_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_14_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_14_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_14_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_14_ce1;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_15_address0;
wire    grp_mmult_hw_float_32_s_fu_74_b_15_ce0;
wire   [5:0] grp_mmult_hw_float_32_s_fu_74_b_15_address1;
wire    grp_mmult_hw_float_32_s_fu_74_b_15_ce1;
wire   [9:0] grp_mmult_hw_float_32_s_fu_74_out_r_address0;
wire    grp_mmult_hw_float_32_s_fu_74_out_r_ce0;
wire    grp_mmult_hw_float_32_s_fu_74_out_r_we0;
wire   [31:0] grp_mmult_hw_float_32_s_fu_74_out_r_d0;
reg    ap_reg_grp_mmult_hw_float_32_s_fu_74_ap_start;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_reg_grp_mmult_hw_float_32_s_fu_74_ap_start = 1'b0;
end

mmult_hw_float_32_s grp_mmult_hw_float_32_s_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mmult_hw_float_32_s_fu_74_ap_start),
    .ap_done(grp_mmult_hw_float_32_s_fu_74_ap_done),
    .ap_idle(grp_mmult_hw_float_32_s_fu_74_ap_idle),
    .ap_ready(grp_mmult_hw_float_32_s_fu_74_ap_ready),
    .a_0_address0(grp_mmult_hw_float_32_s_fu_74_a_0_address0),
    .a_0_ce0(grp_mmult_hw_float_32_s_fu_74_a_0_ce0),
    .a_0_q0(A_0_q0),
    .a_0_address1(grp_mmult_hw_float_32_s_fu_74_a_0_address1),
    .a_0_ce1(grp_mmult_hw_float_32_s_fu_74_a_0_ce1),
    .a_0_q1(A_0_q1),
    .a_1_address0(grp_mmult_hw_float_32_s_fu_74_a_1_address0),
    .a_1_ce0(grp_mmult_hw_float_32_s_fu_74_a_1_ce0),
    .a_1_q0(A_1_q0),
    .a_1_address1(grp_mmult_hw_float_32_s_fu_74_a_1_address1),
    .a_1_ce1(grp_mmult_hw_float_32_s_fu_74_a_1_ce1),
    .a_1_q1(A_1_q1),
    .a_2_address0(grp_mmult_hw_float_32_s_fu_74_a_2_address0),
    .a_2_ce0(grp_mmult_hw_float_32_s_fu_74_a_2_ce0),
    .a_2_q0(A_2_q0),
    .a_2_address1(grp_mmult_hw_float_32_s_fu_74_a_2_address1),
    .a_2_ce1(grp_mmult_hw_float_32_s_fu_74_a_2_ce1),
    .a_2_q1(A_2_q1),
    .a_3_address0(grp_mmult_hw_float_32_s_fu_74_a_3_address0),
    .a_3_ce0(grp_mmult_hw_float_32_s_fu_74_a_3_ce0),
    .a_3_q0(A_3_q0),
    .a_3_address1(grp_mmult_hw_float_32_s_fu_74_a_3_address1),
    .a_3_ce1(grp_mmult_hw_float_32_s_fu_74_a_3_ce1),
    .a_3_q1(A_3_q1),
    .a_4_address0(grp_mmult_hw_float_32_s_fu_74_a_4_address0),
    .a_4_ce0(grp_mmult_hw_float_32_s_fu_74_a_4_ce0),
    .a_4_q0(A_4_q0),
    .a_4_address1(grp_mmult_hw_float_32_s_fu_74_a_4_address1),
    .a_4_ce1(grp_mmult_hw_float_32_s_fu_74_a_4_ce1),
    .a_4_q1(A_4_q1),
    .a_5_address0(grp_mmult_hw_float_32_s_fu_74_a_5_address0),
    .a_5_ce0(grp_mmult_hw_float_32_s_fu_74_a_5_ce0),
    .a_5_q0(A_5_q0),
    .a_5_address1(grp_mmult_hw_float_32_s_fu_74_a_5_address1),
    .a_5_ce1(grp_mmult_hw_float_32_s_fu_74_a_5_ce1),
    .a_5_q1(A_5_q1),
    .a_6_address0(grp_mmult_hw_float_32_s_fu_74_a_6_address0),
    .a_6_ce0(grp_mmult_hw_float_32_s_fu_74_a_6_ce0),
    .a_6_q0(A_6_q0),
    .a_6_address1(grp_mmult_hw_float_32_s_fu_74_a_6_address1),
    .a_6_ce1(grp_mmult_hw_float_32_s_fu_74_a_6_ce1),
    .a_6_q1(A_6_q1),
    .a_7_address0(grp_mmult_hw_float_32_s_fu_74_a_7_address0),
    .a_7_ce0(grp_mmult_hw_float_32_s_fu_74_a_7_ce0),
    .a_7_q0(A_7_q0),
    .a_7_address1(grp_mmult_hw_float_32_s_fu_74_a_7_address1),
    .a_7_ce1(grp_mmult_hw_float_32_s_fu_74_a_7_ce1),
    .a_7_q1(A_7_q1),
    .a_8_address0(grp_mmult_hw_float_32_s_fu_74_a_8_address0),
    .a_8_ce0(grp_mmult_hw_float_32_s_fu_74_a_8_ce0),
    .a_8_q0(A_8_q0),
    .a_8_address1(grp_mmult_hw_float_32_s_fu_74_a_8_address1),
    .a_8_ce1(grp_mmult_hw_float_32_s_fu_74_a_8_ce1),
    .a_8_q1(A_8_q1),
    .a_9_address0(grp_mmult_hw_float_32_s_fu_74_a_9_address0),
    .a_9_ce0(grp_mmult_hw_float_32_s_fu_74_a_9_ce0),
    .a_9_q0(A_9_q0),
    .a_9_address1(grp_mmult_hw_float_32_s_fu_74_a_9_address1),
    .a_9_ce1(grp_mmult_hw_float_32_s_fu_74_a_9_ce1),
    .a_9_q1(A_9_q1),
    .a_10_address0(grp_mmult_hw_float_32_s_fu_74_a_10_address0),
    .a_10_ce0(grp_mmult_hw_float_32_s_fu_74_a_10_ce0),
    .a_10_q0(A_10_q0),
    .a_10_address1(grp_mmult_hw_float_32_s_fu_74_a_10_address1),
    .a_10_ce1(grp_mmult_hw_float_32_s_fu_74_a_10_ce1),
    .a_10_q1(A_10_q1),
    .a_11_address0(grp_mmult_hw_float_32_s_fu_74_a_11_address0),
    .a_11_ce0(grp_mmult_hw_float_32_s_fu_74_a_11_ce0),
    .a_11_q0(A_11_q0),
    .a_11_address1(grp_mmult_hw_float_32_s_fu_74_a_11_address1),
    .a_11_ce1(grp_mmult_hw_float_32_s_fu_74_a_11_ce1),
    .a_11_q1(A_11_q1),
    .a_12_address0(grp_mmult_hw_float_32_s_fu_74_a_12_address0),
    .a_12_ce0(grp_mmult_hw_float_32_s_fu_74_a_12_ce0),
    .a_12_q0(A_12_q0),
    .a_12_address1(grp_mmult_hw_float_32_s_fu_74_a_12_address1),
    .a_12_ce1(grp_mmult_hw_float_32_s_fu_74_a_12_ce1),
    .a_12_q1(A_12_q1),
    .a_13_address0(grp_mmult_hw_float_32_s_fu_74_a_13_address0),
    .a_13_ce0(grp_mmult_hw_float_32_s_fu_74_a_13_ce0),
    .a_13_q0(A_13_q0),
    .a_13_address1(grp_mmult_hw_float_32_s_fu_74_a_13_address1),
    .a_13_ce1(grp_mmult_hw_float_32_s_fu_74_a_13_ce1),
    .a_13_q1(A_13_q1),
    .a_14_address0(grp_mmult_hw_float_32_s_fu_74_a_14_address0),
    .a_14_ce0(grp_mmult_hw_float_32_s_fu_74_a_14_ce0),
    .a_14_q0(A_14_q0),
    .a_14_address1(grp_mmult_hw_float_32_s_fu_74_a_14_address1),
    .a_14_ce1(grp_mmult_hw_float_32_s_fu_74_a_14_ce1),
    .a_14_q1(A_14_q1),
    .a_15_address0(grp_mmult_hw_float_32_s_fu_74_a_15_address0),
    .a_15_ce0(grp_mmult_hw_float_32_s_fu_74_a_15_ce0),
    .a_15_q0(A_15_q0),
    .a_15_address1(grp_mmult_hw_float_32_s_fu_74_a_15_address1),
    .a_15_ce1(grp_mmult_hw_float_32_s_fu_74_a_15_ce1),
    .a_15_q1(A_15_q1),
    .b_0_address0(grp_mmult_hw_float_32_s_fu_74_b_0_address0),
    .b_0_ce0(grp_mmult_hw_float_32_s_fu_74_b_0_ce0),
    .b_0_q0(B_0_q0),
    .b_0_address1(grp_mmult_hw_float_32_s_fu_74_b_0_address1),
    .b_0_ce1(grp_mmult_hw_float_32_s_fu_74_b_0_ce1),
    .b_0_q1(B_0_q1),
    .b_1_address0(grp_mmult_hw_float_32_s_fu_74_b_1_address0),
    .b_1_ce0(grp_mmult_hw_float_32_s_fu_74_b_1_ce0),
    .b_1_q0(B_1_q0),
    .b_1_address1(grp_mmult_hw_float_32_s_fu_74_b_1_address1),
    .b_1_ce1(grp_mmult_hw_float_32_s_fu_74_b_1_ce1),
    .b_1_q1(B_1_q1),
    .b_2_address0(grp_mmult_hw_float_32_s_fu_74_b_2_address0),
    .b_2_ce0(grp_mmult_hw_float_32_s_fu_74_b_2_ce0),
    .b_2_q0(B_2_q0),
    .b_2_address1(grp_mmult_hw_float_32_s_fu_74_b_2_address1),
    .b_2_ce1(grp_mmult_hw_float_32_s_fu_74_b_2_ce1),
    .b_2_q1(B_2_q1),
    .b_3_address0(grp_mmult_hw_float_32_s_fu_74_b_3_address0),
    .b_3_ce0(grp_mmult_hw_float_32_s_fu_74_b_3_ce0),
    .b_3_q0(B_3_q0),
    .b_3_address1(grp_mmult_hw_float_32_s_fu_74_b_3_address1),
    .b_3_ce1(grp_mmult_hw_float_32_s_fu_74_b_3_ce1),
    .b_3_q1(B_3_q1),
    .b_4_address0(grp_mmult_hw_float_32_s_fu_74_b_4_address0),
    .b_4_ce0(grp_mmult_hw_float_32_s_fu_74_b_4_ce0),
    .b_4_q0(B_4_q0),
    .b_4_address1(grp_mmult_hw_float_32_s_fu_74_b_4_address1),
    .b_4_ce1(grp_mmult_hw_float_32_s_fu_74_b_4_ce1),
    .b_4_q1(B_4_q1),
    .b_5_address0(grp_mmult_hw_float_32_s_fu_74_b_5_address0),
    .b_5_ce0(grp_mmult_hw_float_32_s_fu_74_b_5_ce0),
    .b_5_q0(B_5_q0),
    .b_5_address1(grp_mmult_hw_float_32_s_fu_74_b_5_address1),
    .b_5_ce1(grp_mmult_hw_float_32_s_fu_74_b_5_ce1),
    .b_5_q1(B_5_q1),
    .b_6_address0(grp_mmult_hw_float_32_s_fu_74_b_6_address0),
    .b_6_ce0(grp_mmult_hw_float_32_s_fu_74_b_6_ce0),
    .b_6_q0(B_6_q0),
    .b_6_address1(grp_mmult_hw_float_32_s_fu_74_b_6_address1),
    .b_6_ce1(grp_mmult_hw_float_32_s_fu_74_b_6_ce1),
    .b_6_q1(B_6_q1),
    .b_7_address0(grp_mmult_hw_float_32_s_fu_74_b_7_address0),
    .b_7_ce0(grp_mmult_hw_float_32_s_fu_74_b_7_ce0),
    .b_7_q0(B_7_q0),
    .b_7_address1(grp_mmult_hw_float_32_s_fu_74_b_7_address1),
    .b_7_ce1(grp_mmult_hw_float_32_s_fu_74_b_7_ce1),
    .b_7_q1(B_7_q1),
    .b_8_address0(grp_mmult_hw_float_32_s_fu_74_b_8_address0),
    .b_8_ce0(grp_mmult_hw_float_32_s_fu_74_b_8_ce0),
    .b_8_q0(B_8_q0),
    .b_8_address1(grp_mmult_hw_float_32_s_fu_74_b_8_address1),
    .b_8_ce1(grp_mmult_hw_float_32_s_fu_74_b_8_ce1),
    .b_8_q1(B_8_q1),
    .b_9_address0(grp_mmult_hw_float_32_s_fu_74_b_9_address0),
    .b_9_ce0(grp_mmult_hw_float_32_s_fu_74_b_9_ce0),
    .b_9_q0(B_9_q0),
    .b_9_address1(grp_mmult_hw_float_32_s_fu_74_b_9_address1),
    .b_9_ce1(grp_mmult_hw_float_32_s_fu_74_b_9_ce1),
    .b_9_q1(B_9_q1),
    .b_10_address0(grp_mmult_hw_float_32_s_fu_74_b_10_address0),
    .b_10_ce0(grp_mmult_hw_float_32_s_fu_74_b_10_ce0),
    .b_10_q0(B_10_q0),
    .b_10_address1(grp_mmult_hw_float_32_s_fu_74_b_10_address1),
    .b_10_ce1(grp_mmult_hw_float_32_s_fu_74_b_10_ce1),
    .b_10_q1(B_10_q1),
    .b_11_address0(grp_mmult_hw_float_32_s_fu_74_b_11_address0),
    .b_11_ce0(grp_mmult_hw_float_32_s_fu_74_b_11_ce0),
    .b_11_q0(B_11_q0),
    .b_11_address1(grp_mmult_hw_float_32_s_fu_74_b_11_address1),
    .b_11_ce1(grp_mmult_hw_float_32_s_fu_74_b_11_ce1),
    .b_11_q1(B_11_q1),
    .b_12_address0(grp_mmult_hw_float_32_s_fu_74_b_12_address0),
    .b_12_ce0(grp_mmult_hw_float_32_s_fu_74_b_12_ce0),
    .b_12_q0(B_12_q0),
    .b_12_address1(grp_mmult_hw_float_32_s_fu_74_b_12_address1),
    .b_12_ce1(grp_mmult_hw_float_32_s_fu_74_b_12_ce1),
    .b_12_q1(B_12_q1),
    .b_13_address0(grp_mmult_hw_float_32_s_fu_74_b_13_address0),
    .b_13_ce0(grp_mmult_hw_float_32_s_fu_74_b_13_ce0),
    .b_13_q0(B_13_q0),
    .b_13_address1(grp_mmult_hw_float_32_s_fu_74_b_13_address1),
    .b_13_ce1(grp_mmult_hw_float_32_s_fu_74_b_13_ce1),
    .b_13_q1(B_13_q1),
    .b_14_address0(grp_mmult_hw_float_32_s_fu_74_b_14_address0),
    .b_14_ce0(grp_mmult_hw_float_32_s_fu_74_b_14_ce0),
    .b_14_q0(B_14_q0),
    .b_14_address1(grp_mmult_hw_float_32_s_fu_74_b_14_address1),
    .b_14_ce1(grp_mmult_hw_float_32_s_fu_74_b_14_ce1),
    .b_14_q1(B_14_q1),
    .b_15_address0(grp_mmult_hw_float_32_s_fu_74_b_15_address0),
    .b_15_ce0(grp_mmult_hw_float_32_s_fu_74_b_15_ce0),
    .b_15_q0(B_15_q0),
    .b_15_address1(grp_mmult_hw_float_32_s_fu_74_b_15_address1),
    .b_15_ce1(grp_mmult_hw_float_32_s_fu_74_b_15_ce1),
    .b_15_q1(B_15_q1),
    .out_r_address0(grp_mmult_hw_float_32_s_fu_74_out_r_address0),
    .out_r_ce0(grp_mmult_hw_float_32_s_fu_74_out_r_ce0),
    .out_r_we0(grp_mmult_hw_float_32_s_fu_74_out_r_we0),
    .out_r_d0(grp_mmult_hw_float_32_s_fu_74_out_r_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_mmult_hw_float_32_s_fu_74_ap_start <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_reg_grp_mmult_hw_float_32_s_fu_74_ap_start <= 1'b1;
        end else if ((grp_mmult_hw_float_32_s_fu_74_ap_ready == 1'b1)) begin
            ap_reg_grp_mmult_hw_float_32_s_fu_74_ap_start <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((grp_mmult_hw_float_32_s_fu_74_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_mmult_hw_float_32_s_fu_74_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_mmult_hw_float_32_s_fu_74_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_0_address0 = grp_mmult_hw_float_32_s_fu_74_a_0_address0;

assign A_0_address1 = grp_mmult_hw_float_32_s_fu_74_a_0_address1;

assign A_0_ce0 = grp_mmult_hw_float_32_s_fu_74_a_0_ce0;

assign A_0_ce1 = grp_mmult_hw_float_32_s_fu_74_a_0_ce1;

assign A_10_address0 = grp_mmult_hw_float_32_s_fu_74_a_10_address0;

assign A_10_address1 = grp_mmult_hw_float_32_s_fu_74_a_10_address1;

assign A_10_ce0 = grp_mmult_hw_float_32_s_fu_74_a_10_ce0;

assign A_10_ce1 = grp_mmult_hw_float_32_s_fu_74_a_10_ce1;

assign A_11_address0 = grp_mmult_hw_float_32_s_fu_74_a_11_address0;

assign A_11_address1 = grp_mmult_hw_float_32_s_fu_74_a_11_address1;

assign A_11_ce0 = grp_mmult_hw_float_32_s_fu_74_a_11_ce0;

assign A_11_ce1 = grp_mmult_hw_float_32_s_fu_74_a_11_ce1;

assign A_12_address0 = grp_mmult_hw_float_32_s_fu_74_a_12_address0;

assign A_12_address1 = grp_mmult_hw_float_32_s_fu_74_a_12_address1;

assign A_12_ce0 = grp_mmult_hw_float_32_s_fu_74_a_12_ce0;

assign A_12_ce1 = grp_mmult_hw_float_32_s_fu_74_a_12_ce1;

assign A_13_address0 = grp_mmult_hw_float_32_s_fu_74_a_13_address0;

assign A_13_address1 = grp_mmult_hw_float_32_s_fu_74_a_13_address1;

assign A_13_ce0 = grp_mmult_hw_float_32_s_fu_74_a_13_ce0;

assign A_13_ce1 = grp_mmult_hw_float_32_s_fu_74_a_13_ce1;

assign A_14_address0 = grp_mmult_hw_float_32_s_fu_74_a_14_address0;

assign A_14_address1 = grp_mmult_hw_float_32_s_fu_74_a_14_address1;

assign A_14_ce0 = grp_mmult_hw_float_32_s_fu_74_a_14_ce0;

assign A_14_ce1 = grp_mmult_hw_float_32_s_fu_74_a_14_ce1;

assign A_15_address0 = grp_mmult_hw_float_32_s_fu_74_a_15_address0;

assign A_15_address1 = grp_mmult_hw_float_32_s_fu_74_a_15_address1;

assign A_15_ce0 = grp_mmult_hw_float_32_s_fu_74_a_15_ce0;

assign A_15_ce1 = grp_mmult_hw_float_32_s_fu_74_a_15_ce1;

assign A_1_address0 = grp_mmult_hw_float_32_s_fu_74_a_1_address0;

assign A_1_address1 = grp_mmult_hw_float_32_s_fu_74_a_1_address1;

assign A_1_ce0 = grp_mmult_hw_float_32_s_fu_74_a_1_ce0;

assign A_1_ce1 = grp_mmult_hw_float_32_s_fu_74_a_1_ce1;

assign A_2_address0 = grp_mmult_hw_float_32_s_fu_74_a_2_address0;

assign A_2_address1 = grp_mmult_hw_float_32_s_fu_74_a_2_address1;

assign A_2_ce0 = grp_mmult_hw_float_32_s_fu_74_a_2_ce0;

assign A_2_ce1 = grp_mmult_hw_float_32_s_fu_74_a_2_ce1;

assign A_3_address0 = grp_mmult_hw_float_32_s_fu_74_a_3_address0;

assign A_3_address1 = grp_mmult_hw_float_32_s_fu_74_a_3_address1;

assign A_3_ce0 = grp_mmult_hw_float_32_s_fu_74_a_3_ce0;

assign A_3_ce1 = grp_mmult_hw_float_32_s_fu_74_a_3_ce1;

assign A_4_address0 = grp_mmult_hw_float_32_s_fu_74_a_4_address0;

assign A_4_address1 = grp_mmult_hw_float_32_s_fu_74_a_4_address1;

assign A_4_ce0 = grp_mmult_hw_float_32_s_fu_74_a_4_ce0;

assign A_4_ce1 = grp_mmult_hw_float_32_s_fu_74_a_4_ce1;

assign A_5_address0 = grp_mmult_hw_float_32_s_fu_74_a_5_address0;

assign A_5_address1 = grp_mmult_hw_float_32_s_fu_74_a_5_address1;

assign A_5_ce0 = grp_mmult_hw_float_32_s_fu_74_a_5_ce0;

assign A_5_ce1 = grp_mmult_hw_float_32_s_fu_74_a_5_ce1;

assign A_6_address0 = grp_mmult_hw_float_32_s_fu_74_a_6_address0;

assign A_6_address1 = grp_mmult_hw_float_32_s_fu_74_a_6_address1;

assign A_6_ce0 = grp_mmult_hw_float_32_s_fu_74_a_6_ce0;

assign A_6_ce1 = grp_mmult_hw_float_32_s_fu_74_a_6_ce1;

assign A_7_address0 = grp_mmult_hw_float_32_s_fu_74_a_7_address0;

assign A_7_address1 = grp_mmult_hw_float_32_s_fu_74_a_7_address1;

assign A_7_ce0 = grp_mmult_hw_float_32_s_fu_74_a_7_ce0;

assign A_7_ce1 = grp_mmult_hw_float_32_s_fu_74_a_7_ce1;

assign A_8_address0 = grp_mmult_hw_float_32_s_fu_74_a_8_address0;

assign A_8_address1 = grp_mmult_hw_float_32_s_fu_74_a_8_address1;

assign A_8_ce0 = grp_mmult_hw_float_32_s_fu_74_a_8_ce0;

assign A_8_ce1 = grp_mmult_hw_float_32_s_fu_74_a_8_ce1;

assign A_9_address0 = grp_mmult_hw_float_32_s_fu_74_a_9_address0;

assign A_9_address1 = grp_mmult_hw_float_32_s_fu_74_a_9_address1;

assign A_9_ce0 = grp_mmult_hw_float_32_s_fu_74_a_9_ce0;

assign A_9_ce1 = grp_mmult_hw_float_32_s_fu_74_a_9_ce1;

assign B_0_address0 = grp_mmult_hw_float_32_s_fu_74_b_0_address0;

assign B_0_address1 = grp_mmult_hw_float_32_s_fu_74_b_0_address1;

assign B_0_ce0 = grp_mmult_hw_float_32_s_fu_74_b_0_ce0;

assign B_0_ce1 = grp_mmult_hw_float_32_s_fu_74_b_0_ce1;

assign B_10_address0 = grp_mmult_hw_float_32_s_fu_74_b_10_address0;

assign B_10_address1 = grp_mmult_hw_float_32_s_fu_74_b_10_address1;

assign B_10_ce0 = grp_mmult_hw_float_32_s_fu_74_b_10_ce0;

assign B_10_ce1 = grp_mmult_hw_float_32_s_fu_74_b_10_ce1;

assign B_11_address0 = grp_mmult_hw_float_32_s_fu_74_b_11_address0;

assign B_11_address1 = grp_mmult_hw_float_32_s_fu_74_b_11_address1;

assign B_11_ce0 = grp_mmult_hw_float_32_s_fu_74_b_11_ce0;

assign B_11_ce1 = grp_mmult_hw_float_32_s_fu_74_b_11_ce1;

assign B_12_address0 = grp_mmult_hw_float_32_s_fu_74_b_12_address0;

assign B_12_address1 = grp_mmult_hw_float_32_s_fu_74_b_12_address1;

assign B_12_ce0 = grp_mmult_hw_float_32_s_fu_74_b_12_ce0;

assign B_12_ce1 = grp_mmult_hw_float_32_s_fu_74_b_12_ce1;

assign B_13_address0 = grp_mmult_hw_float_32_s_fu_74_b_13_address0;

assign B_13_address1 = grp_mmult_hw_float_32_s_fu_74_b_13_address1;

assign B_13_ce0 = grp_mmult_hw_float_32_s_fu_74_b_13_ce0;

assign B_13_ce1 = grp_mmult_hw_float_32_s_fu_74_b_13_ce1;

assign B_14_address0 = grp_mmult_hw_float_32_s_fu_74_b_14_address0;

assign B_14_address1 = grp_mmult_hw_float_32_s_fu_74_b_14_address1;

assign B_14_ce0 = grp_mmult_hw_float_32_s_fu_74_b_14_ce0;

assign B_14_ce1 = grp_mmult_hw_float_32_s_fu_74_b_14_ce1;

assign B_15_address0 = grp_mmult_hw_float_32_s_fu_74_b_15_address0;

assign B_15_address1 = grp_mmult_hw_float_32_s_fu_74_b_15_address1;

assign B_15_ce0 = grp_mmult_hw_float_32_s_fu_74_b_15_ce0;

assign B_15_ce1 = grp_mmult_hw_float_32_s_fu_74_b_15_ce1;

assign B_1_address0 = grp_mmult_hw_float_32_s_fu_74_b_1_address0;

assign B_1_address1 = grp_mmult_hw_float_32_s_fu_74_b_1_address1;

assign B_1_ce0 = grp_mmult_hw_float_32_s_fu_74_b_1_ce0;

assign B_1_ce1 = grp_mmult_hw_float_32_s_fu_74_b_1_ce1;

assign B_2_address0 = grp_mmult_hw_float_32_s_fu_74_b_2_address0;

assign B_2_address1 = grp_mmult_hw_float_32_s_fu_74_b_2_address1;

assign B_2_ce0 = grp_mmult_hw_float_32_s_fu_74_b_2_ce0;

assign B_2_ce1 = grp_mmult_hw_float_32_s_fu_74_b_2_ce1;

assign B_3_address0 = grp_mmult_hw_float_32_s_fu_74_b_3_address0;

assign B_3_address1 = grp_mmult_hw_float_32_s_fu_74_b_3_address1;

assign B_3_ce0 = grp_mmult_hw_float_32_s_fu_74_b_3_ce0;

assign B_3_ce1 = grp_mmult_hw_float_32_s_fu_74_b_3_ce1;

assign B_4_address0 = grp_mmult_hw_float_32_s_fu_74_b_4_address0;

assign B_4_address1 = grp_mmult_hw_float_32_s_fu_74_b_4_address1;

assign B_4_ce0 = grp_mmult_hw_float_32_s_fu_74_b_4_ce0;

assign B_4_ce1 = grp_mmult_hw_float_32_s_fu_74_b_4_ce1;

assign B_5_address0 = grp_mmult_hw_float_32_s_fu_74_b_5_address0;

assign B_5_address1 = grp_mmult_hw_float_32_s_fu_74_b_5_address1;

assign B_5_ce0 = grp_mmult_hw_float_32_s_fu_74_b_5_ce0;

assign B_5_ce1 = grp_mmult_hw_float_32_s_fu_74_b_5_ce1;

assign B_6_address0 = grp_mmult_hw_float_32_s_fu_74_b_6_address0;

assign B_6_address1 = grp_mmult_hw_float_32_s_fu_74_b_6_address1;

assign B_6_ce0 = grp_mmult_hw_float_32_s_fu_74_b_6_ce0;

assign B_6_ce1 = grp_mmult_hw_float_32_s_fu_74_b_6_ce1;

assign B_7_address0 = grp_mmult_hw_float_32_s_fu_74_b_7_address0;

assign B_7_address1 = grp_mmult_hw_float_32_s_fu_74_b_7_address1;

assign B_7_ce0 = grp_mmult_hw_float_32_s_fu_74_b_7_ce0;

assign B_7_ce1 = grp_mmult_hw_float_32_s_fu_74_b_7_ce1;

assign B_8_address0 = grp_mmult_hw_float_32_s_fu_74_b_8_address0;

assign B_8_address1 = grp_mmult_hw_float_32_s_fu_74_b_8_address1;

assign B_8_ce0 = grp_mmult_hw_float_32_s_fu_74_b_8_ce0;

assign B_8_ce1 = grp_mmult_hw_float_32_s_fu_74_b_8_ce1;

assign B_9_address0 = grp_mmult_hw_float_32_s_fu_74_b_9_address0;

assign B_9_address1 = grp_mmult_hw_float_32_s_fu_74_b_9_address1;

assign B_9_ce0 = grp_mmult_hw_float_32_s_fu_74_b_9_ce0;

assign B_9_ce1 = grp_mmult_hw_float_32_s_fu_74_b_9_ce1;

assign C_address0 = grp_mmult_hw_float_32_s_fu_74_out_r_address0;

assign C_ce0 = grp_mmult_hw_float_32_s_fu_74_out_r_ce0;

assign C_d0 = grp_mmult_hw_float_32_s_fu_74_out_r_d0;

assign C_we0 = grp_mmult_hw_float_32_s_fu_74_out_r_we0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_mmult_hw_float_32_s_fu_74_ap_start = ap_reg_grp_mmult_hw_float_32_s_fu_74_ap_start;

endmodule //standalone_mmult
