-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity standalone_mmult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_ce1 : OUT STD_LOGIC;
    A_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_ce1 : OUT STD_LOGIC;
    B_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_we0 : OUT STD_LOGIC;
    C_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of standalone_mmult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "standalone_mmult,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.317400,HLS_SYN_LAT=16537,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=10,HLS_SYN_FF=4555,HLS_SYN_LUT=4033}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_mmult_hw_float_32_s_fu_14_ap_start : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_ap_done : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_ap_idle : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_ap_ready : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_a_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mmult_hw_float_32_s_fu_14_a_ce0 : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_a_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mmult_hw_float_32_s_fu_14_a_ce1 : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_b_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mmult_hw_float_32_s_fu_14_b_ce0 : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_b_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mmult_hw_float_32_s_fu_14_b_ce1 : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_mmult_hw_float_32_s_fu_14_out_r_ce0 : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_out_r_we0 : STD_LOGIC;
    signal grp_mmult_hw_float_32_s_fu_14_out_r_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_grp_mmult_hw_float_32_s_fu_14_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component mmult_hw_float_32_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        a_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        a_ce0 : OUT STD_LOGIC;
        a_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        a_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        a_ce1 : OUT STD_LOGIC;
        a_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        b_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        b_ce0 : OUT STD_LOGIC;
        b_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        b_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        b_ce1 : OUT STD_LOGIC;
        b_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_mmult_hw_float_32_s_fu_14 : component mmult_hw_float_32_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mmult_hw_float_32_s_fu_14_ap_start,
        ap_done => grp_mmult_hw_float_32_s_fu_14_ap_done,
        ap_idle => grp_mmult_hw_float_32_s_fu_14_ap_idle,
        ap_ready => grp_mmult_hw_float_32_s_fu_14_ap_ready,
        a_address0 => grp_mmult_hw_float_32_s_fu_14_a_address0,
        a_ce0 => grp_mmult_hw_float_32_s_fu_14_a_ce0,
        a_q0 => A_q0,
        a_address1 => grp_mmult_hw_float_32_s_fu_14_a_address1,
        a_ce1 => grp_mmult_hw_float_32_s_fu_14_a_ce1,
        a_q1 => A_q1,
        b_address0 => grp_mmult_hw_float_32_s_fu_14_b_address0,
        b_ce0 => grp_mmult_hw_float_32_s_fu_14_b_ce0,
        b_q0 => B_q0,
        b_address1 => grp_mmult_hw_float_32_s_fu_14_b_address1,
        b_ce1 => grp_mmult_hw_float_32_s_fu_14_b_ce1,
        b_q1 => B_q1,
        out_r_address0 => grp_mmult_hw_float_32_s_fu_14_out_r_address0,
        out_r_ce0 => grp_mmult_hw_float_32_s_fu_14_out_r_ce0,
        out_r_we0 => grp_mmult_hw_float_32_s_fu_14_out_r_we0,
        out_r_d0 => grp_mmult_hw_float_32_s_fu_14_out_r_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_mmult_hw_float_32_s_fu_14_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_mmult_hw_float_32_s_fu_14_ap_start <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_reg_grp_mmult_hw_float_32_s_fu_14_ap_start <= ap_const_logic_1;
                elsif ((grp_mmult_hw_float_32_s_fu_14_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_mmult_hw_float_32_s_fu_14_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_mmult_hw_float_32_s_fu_14_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_mmult_hw_float_32_s_fu_14_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    A_address0 <= grp_mmult_hw_float_32_s_fu_14_a_address0;
    A_address1 <= grp_mmult_hw_float_32_s_fu_14_a_address1;
    A_ce0 <= grp_mmult_hw_float_32_s_fu_14_a_ce0;
    A_ce1 <= grp_mmult_hw_float_32_s_fu_14_a_ce1;
    B_address0 <= grp_mmult_hw_float_32_s_fu_14_b_address0;
    B_address1 <= grp_mmult_hw_float_32_s_fu_14_b_address1;
    B_ce0 <= grp_mmult_hw_float_32_s_fu_14_b_ce0;
    B_ce1 <= grp_mmult_hw_float_32_s_fu_14_b_ce1;
    C_address0 <= grp_mmult_hw_float_32_s_fu_14_out_r_address0;
    C_ce0 <= grp_mmult_hw_float_32_s_fu_14_out_r_ce0;
    C_d0 <= grp_mmult_hw_float_32_s_fu_14_out_r_d0;
    C_we0 <= grp_mmult_hw_float_32_s_fu_14_out_r_we0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(grp_mmult_hw_float_32_s_fu_14_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_mmult_hw_float_32_s_fu_14_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_mmult_hw_float_32_s_fu_14_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_mmult_hw_float_32_s_fu_14_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_mmult_hw_float_32_s_fu_14_ap_start <= ap_reg_grp_mmult_hw_float_32_s_fu_14_ap_start;
end behav;
